//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 10:42:22 PM GMT 
//


package com.corbo.musicstreaming.model.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for albumCplxType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="albumCplxType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="albumName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="albumUuid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="artistUuid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="trackList" type="{}trackList"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "albumCplxType", propOrder = {
    "albumName",
    "albumUuid",
    "artistUuid",
    "trackList"
})
public class AlbumCplxType {

    @XmlElement(required = true)
    protected String albumName;
    @XmlElement(required = true)
    protected String albumUuid;
    @XmlElement(required = true)
    protected String artistUuid;
    @XmlElement(required = true)
    protected TrackList trackList;

    /**
     * Gets the value of the albumName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlbumName() {
        return albumName;
    }

    /**
     * Sets the value of the albumName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlbumName(String value) {
        this.albumName = value;
    }

    /**
     * Gets the value of the albumUuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlbumUuid() {
        return albumUuid;
    }

    /**
     * Sets the value of the albumUuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlbumUuid(String value) {
        this.albumUuid = value;
    }

    /**
     * Gets the value of the artistUuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArtistUuid() {
        return artistUuid;
    }

    /**
     * Sets the value of the artistUuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArtistUuid(String value) {
        this.artistUuid = value;
    }

    /**
     * Gets the value of the trackList property.
     * 
     * @return
     *     possible object is
     *     {@link TrackList }
     *     
     */
    public TrackList getTrackList() {
        return trackList;
    }

    /**
     * Sets the value of the trackList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrackList }
     *     
     */
    public void setTrackList(TrackList value) {
        this.trackList = value;
    }

}
